/*************************************************************************
    > File Name: Easy_389.cpp
    > Author: 张保佳
    > Mail: mg1433078@smail.nju.edu.cn 
    > Created Time: 2016年09月03日 星期六 10时02分03秒
	
	>Given two strings s and t which consist of only lowercase letters.
	>String t is generated by random shuffling string s and then add one more letter at a random position.
	>Find the letter that was added in t.
	>Example:
	>Input:
	>s = "abcd"
	>t = "abcde"
	>Output:
	>e
	>Explanation:
	>'e' is the letter that was added.
 ************************************************************************/

#include<iostream>
#include<string>
using namespace std;

class Find_The_Difference{
	public:
		char findTheDifference(string s,string t)
		{
			int *sLetter=new int[26]();
			int *tLetter=new int[26]();

			for(int i=0;i<s.size();i++)
			{
				sLetter[s[i]-'a']++;
			}

			for(int i=0;i<t.size();i++)
			{
				tLetter[t[i]-'a']++;
			}

			for(int i=0;i<26;i++)
			{
				if(tLetter[i]>sLetter[i])
					return (char)(i+'a');
			}
		}
};

int main()
{
	
	Find_The_Difference Test;
	auto result = Test.findTheDifference("abcd","abcdh");
	cout<<"result = "<<result<<endl;
	return 0;
}

