LeetCode:LeetCode.o
	g++ -g -std=c++11 -o LeetCode LeetCode.o

LeetCode.o:File_ListNode.h A_Binary_Search.h File_TreeLinkNode.h \
	A_Template_Test.h A_FileStream.h File_UndirectedGraphNode.h \
	Hard_214.h
	g++ -g -std=c++11 -c LeetCode.cpp

clean:
	rm LeetCode LeetCode.o
	
all:
	@echo name="LeetCode Test"
	
